[INSTRUMENT]
# Instrument in wich is plugged the 7708 switching module
# (e.g.: "ASRL1::INSTR", "TCPIP::192.168.01.01::1394::SOCKET")
rsrc_name = ""

[MODULE]
module_name = 7708

[CHANNELS]
## Thermocouple config example
# [CHANNELS.101]
# mode = "temp"
# transducer = "tc"
# type = "K"
# ref_junction = "int"
# resolution = 6
# nplc = 5
101 = {}
102 = {}
103 = {}
104 = {}
105 = {}
106 = {}
107 = {}
108 = {}
109 = {}
110 = {}
111 = {}
112 = {}
113 = {}
114 = {}
115 = {}
116 = {}
117 = {}
118 = {}
119 = {}
120 = {}
121 = {}
122 = {}
123 = {}
124 = {}
125 = {}
126 = {}
127 = {}
128 = {}
129 = {}
130 = {}
131 = {}
132 = {}
133 = {}
134 = {}
135 = {}
136 = {}
137 = {}
138 = {}
139 = {}
140 = {}